
spring:
  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: labs64
    password: labs64pw

  datasource:
    url: jdbc:postgresql://localhost:5432/checkout
    username: labs64
    password: labs64pw

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration